parameters:

services:
    _defaults:
        autowire: true      # Automatically inject dependencies (e.g., LoggerInterface)
        autoconfigure: true # Automatically apply relevant configuration (e.g., controller service)

    # Registers all services in the App namespace except the specified ones
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/*'
            - '../src/Entity/*'
            - '../src/Kernel.php'
        public: false  # Keep services private by default, but specify public for controllers if needed

    # Explicit service configuration for the LoginController
    App\Controller\LoginController:
        public: true
        tags:
            - { name: 'controller.service_arguments' } # Ensure controller arguments are injected
